language: php
php:
  - 5.3
before_install:
  - git clone https://github.com/abraham/twitteroauth.git
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
